version: "3"
services:
  database:
    image: postgres:16.0-bookworm
    container_name: course_db
    volumes:
      - postgresdata:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
    ports:
      - 5432:5432

  currency_course:
    image: ${RATEROVER_IMAGE:-raterover}
    build:
      context: .
    container_name: currency_course_app
    depends_on:
      - database
    command: ["currency_course", "run"]
    healthcheck:
      test: curl --fail http://localhost:8000/health
    ports:
      - 7777:8000

volumes:
  postgresdata: