version: "3"
services:
  database:
    image: postgres:16.0-bookworm
    container_name: course_db
    volumes:
      - postgresdata:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]


  currency_course:
    build: .
    container_name: currency_course_app
    environment:
      DB_DSN: ${CURRENCE_COURSE_DB_DSN:-postgresql+asyncpg://postgres:postgres@database:5432/currency_course}
    depends_on:
      - database
    command: bash -c "sleep 20 && poetry run python -m raterover currency_course database migrations apply && poetry run python -m raterover currency_course run"

    ports:
      - 7777:8000

volumes:
  postgresdata:

